/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Schema,
} from './components/form/form';

export namespace Components {
  interface RfkSignature {
    'fieldName': any;
    'value': any;
  }
  interface RfkodeForm {
    'data': Object;
    'schema': Schema;
  }
}

declare global {


  interface HTMLRfkSignatureElement extends Components.RfkSignature, HTMLStencilElement {}
  var HTMLRfkSignatureElement: {
    prototype: HTMLRfkSignatureElement;
    new (): HTMLRfkSignatureElement;
  };

  interface HTMLRfkodeFormElement extends Components.RfkodeForm, HTMLStencilElement {}
  var HTMLRfkodeFormElement: {
    prototype: HTMLRfkodeFormElement;
    new (): HTMLRfkodeFormElement;
  };
  interface HTMLElementTagNameMap {
    'rfk-signature': HTMLRfkSignatureElement;
    'rfkode-form': HTMLRfkodeFormElement;
  }
}

declare namespace LocalJSX {
  interface RfkSignature {
    'fieldName'?: any;
    'value'?: any;
  }
  interface RfkodeForm {
    'data'?: Object;
    'onAttachmentChanged'?: (event: CustomEvent<any>) => void;
    'onDataChanged'?: (event: CustomEvent<any>) => void;
    'onRelatedElementAction'?: (event: CustomEvent<any>) => void;
    'schema'?: Schema;
  }

  interface IntrinsicElements {
    'rfk-signature': RfkSignature;
    'rfkode-form': RfkodeForm;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'rfk-signature': LocalJSX.RfkSignature & JSXBase.HTMLAttributes<HTMLRfkSignatureElement>;
      'rfkode-form': LocalJSX.RfkodeForm & JSXBase.HTMLAttributes<HTMLRfkodeFormElement>;
    }
  }
}


